/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PopUps;

import classes.customer;
import java.awt.Window;
import java.sql.ResultSet;
import javax.swing.BorderFactory;
import javax.swing.JScrollPane;

/**
 *
 * @author Lasith
 */
public class selectCustomer extends javax.swing.JDialog {

    /**
     * Creates new form selectCustomer
     */
    private String cusID;
    private String cusName = "Guest";
    public selectCustomer() {
        super((Window)null);
        setModal(true);
        initComponents();
    }
    public String getCusID(){
        return cusID;
    }
    public String getCusName(){
        return cusName;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        NameTxt = new javax.swing.JLabel();
        NICText = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        NICDisplay = new javax.swing.JTextArea();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        NameDisplay = new javax.swing.JTextArea();
        list = new javax.swing.JTable();
        okayButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        addNew = new javax.swing.JButton();

        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(220, 255, 247));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NameTxt.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        NameTxt.setText("Name:");
        jPanel3.add(NameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 90, 60));

        NICText.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        NICText.setText("NIC:");
        jPanel3.add(NICText, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 12, 70, 23));

        jScrollPane3.setForeground(new java.awt.Color(255, 255, 255));

        NICDisplay.setBackground(new java.awt.Color(220, 255, 247));
        NICDisplay.setColumns(5);
        NICDisplay.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        NICDisplay.setLineWrap(true);
        NICDisplay.setRows(1);
        NICDisplay.setTabSize(1);
        NICDisplay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(210, 255, 255)));
        NICDisplay.setCaretColor(new java.awt.Color(164, 223, 252));
        NICDisplay.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NICDisplayKeyPressed(evt);
            }
        });
        jScrollPane3.setViewportView(NICDisplay);

        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 270, 30));

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NameDisplay.setEditable(false);
        NameDisplay.setBackground(new java.awt.Color(220, 255, 247));
        NameDisplay.setColumns(31);
        NameDisplay.setLineWrap(true);
        NameDisplay.setRows(4);
        NameDisplay.setTabSize(1);
        NameDisplay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 204)));
        NameDisplay.setCaretColor(new java.awt.Color(164, 223, 252));
        jLayeredPane1.add(NameDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 140));

        JScrollPane sp = new JScrollPane(list);
        sp.setBorder(BorderFactory.createEmptyBorder());
        list.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                ""
            }
        ));
        list.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listMouseClicked(evt);
            }
        });
        jLayeredPane1.add(list, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 150));

        jPanel3.add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 270, 140));

        okayButton.setBackground(new java.awt.Color(51, 153, 0));
        okayButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        okayButton.setForeground(new java.awt.Color(255, 255, 255));
        okayButton.setText("OKAY");
        okayButton.setBorder(null);
        okayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okayButtonActionPerformed(evt);
            }
        });

        cancelButton.setBackground(new java.awt.Color(102, 153, 255));
        cancelButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cancelButton.setForeground(new java.awt.Color(255, 255, 255));
        cancelButton.setText("Cancel");
        cancelButton.setBorder(null);
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setText("Select Customer");

        addNew.setBackground(new java.awt.Color(255, 0, 0));
        addNew.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        addNew.setForeground(new java.awt.Color(255, 255, 255));
        addNew.setText("New Cus");
        addNew.setBorder(null);
        addNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(addNew, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(okayButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okayButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addNew, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void okayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okayButtonActionPerformed
        cusName = customer.getName(NICDisplay.getText());
        if ("Guest".equals(cusName)){
            cusID = null;
        }else{
            cusID = NICDisplay.getText();
        }
        this.dispose();
    }//GEN-LAST:event_okayButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void NICDisplayKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NICDisplayKeyPressed
        // TODO add your handling code here:
        customer.searchCustomer(NICDisplay.getText(),list);
        NameDisplay.setVisible(false);
        list.setVisible(true);
        
        
    }//GEN-LAST:event_NICDisplayKeyPressed

    private void listMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listMouseClicked
        // TODO add your handling code here:
        NICDisplay.setText(list.getValueAt(list.getSelectedRow(), 0).toString());
        NameDisplay.setText(customer.getName(NICDisplay.getText()));
        list.setVisible(false);
        NameDisplay.setVisible(true);
    }//GEN-LAST:event_listMouseClicked

    private void addNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewActionPerformed
        // TODO add your handling code here:
        new AddNewCustomer().setVisible(true);
    }//GEN-LAST:event_addNewActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(selectCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(selectCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(selectCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(selectCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new selectCustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea NICDisplay;
    private javax.swing.JLabel NICText;
    private javax.swing.JTextArea NameDisplay;
    private javax.swing.JLabel NameTxt;
    private javax.swing.JButton addNew;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable list;
    private javax.swing.JButton okayButton;
    // End of variables declaration//GEN-END:variables
}
