/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;
import Alerts.*;
import Errors.dbError;
import Errors.dbErrorNonExitOnClose;
import PopUps.ItemDetailsPopUp;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.table.DefaultTableModel;
import Graphics.jPanelGradient;
import PopUps.ShowCustomers;
import PopUps.selectCustomer;
import classes.Clock;
import classes.Payment;
import classes.Product;
import classes.payment_details;
import java.sql.SQLException;
/**
 *
 * @author Lasith
 */
public class BillingInterface extends javax.swing.JFrame {

    /**
     * Creates new form Billing
     */
    private String CusID=null;
    private String UsrID;
    public BillingInterface() {
        initComponents();
        try{
            reciptNoText.setText(Integer.toString(Payment.getID()));
            if (reciptNoText.getText().equals("0")){
                throw new SQLException();
            }
        }catch(SQLException e){
            new dbError().setVisible(true);
        }
        setDate();
        qtyInputLabel.setText("1");
        Clock.showTime(timeLabel,timeText);
    }

    public BillingInterface(String user,String usrID) {
        initComponents();
        setDate();
        Clock.showTime(timeLabel,timeText);
        UsrID = usrID;
        jLabel4.setText(user);
        cashierNameText.setText(user);
        qtyInputLabel.setText("1");
        try{
            reciptNoText.setText(Integer.toString(Payment.getID()));
            if (reciptNoText.getText().equals("0")){
                throw new SQLException();
            }
        }catch(SQLException e){
            new dbError().setVisible(true);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel3 = new jPanelGradient(134,143,150,89,97,100);
        NewOrder = new javax.swing.JPanel();
        newOrderIcon = new javax.swing.JLabel();
        newOrderText = new javax.swing.JLabel();
        CustomerPanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        LogoutPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        HoldOrderPanel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        geelsSuperLabel = new javax.swing.JLabel();
        LoadOrderPanel1 = new javax.swing.JPanel();
        LoadOrderLable = new javax.swing.JLabel();
        LoadOrderIcon = new javax.swing.JLabel();
        jPanel1 = new jPanelGradient(41,50,60,72,85,99);
        jPanel2 = new jPanelGradient(41,50,60,72,85,99);
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        timeLabel = new javax.swing.JLabel();
        homeIcon = new javax.swing.JLabel();
        printIcon = new javax.swing.JLabel();
        userIcon = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        rslable = new javax.swing.JLabel();
        TotalText = new javax.swing.JLabel();
        totalLable = new javax.swing.JLabel();
        billHeading = new jPanelGradient(41,50,60,72,85,99);
        lableReciptNo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        reciptNoText = new javax.swing.JLabel();
        dateText = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cashierNameText = new javax.swing.JLabel();
        customerLabel = new javax.swing.JLabel();
        timeText = new javax.swing.JLabel();
        customerTxt = new javax.swing.JLabel();
        BillPanel = new jPanelGradient(41,50,60,72,85,99);
        scanLabel = new javax.swing.JLabel();
        codeInput = new javax.swing.JTextField();
        qtyLabel = new javax.swing.JLabel();
        qtyInputLabel = new javax.swing.JTextField();
        insertPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        AddCusPanel = new javax.swing.JPanel();
        AddCusLabel = new javax.swing.JLabel();
        AddCusIcon = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DisplayItems = new javax.swing.JTable();
        ItemDetailsAreaPanel = new jPanelGradient(41,50,60,72,85,99);
        ItemIDText = new javax.swing.JLabel();
        ItemNameLabel = new javax.swing.JLabel();
        ItemTypeLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ItemNameDisplay = new javax.swing.JTextArea();
        ItemTypeDisplay = new javax.swing.JTextField();
        ItemIDDisplay1 = new javax.swing.JTextField();
        printPanel = new javax.swing.JPanel();
        PrintBill = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(99, 110, 114));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NewOrder.setBackground(new java.awt.Color(99, 110, 114));
        NewOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NewOrderMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NewOrderMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                NewOrderMouseExited(evt);
            }
        });

        newOrderIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/BillingIMGs/icons8_transaction_60px.png"))); // NOI18N

        newOrderText.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        newOrderText.setForeground(new java.awt.Color(255, 255, 255));
        newOrderText.setText(" New Order");

        javax.swing.GroupLayout NewOrderLayout = new javax.swing.GroupLayout(NewOrder);
        NewOrder.setLayout(NewOrderLayout);
        NewOrderLayout.setHorizontalGroup(
            NewOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewOrderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(newOrderIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newOrderText, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                .addContainerGap())
        );
        NewOrderLayout.setVerticalGroup(
            NewOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewOrderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NewOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(newOrderIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(newOrderText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(NewOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 156, 250, -1));

        CustomerPanel.setBackground(new java.awt.Color(99, 110, 114));
        CustomerPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CustomerPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CustomerPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CustomerPanelMouseExited(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Customers");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/BillingIMGs/icons8_user_groups_64px.png"))); // NOI18N

        javax.swing.GroupLayout CustomerPanelLayout = new javax.swing.GroupLayout(CustomerPanel);
        CustomerPanel.setLayout(CustomerPanelLayout);
        CustomerPanelLayout.setHorizontalGroup(
            CustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CustomerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        CustomerPanelLayout.setVerticalGroup(
            CustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CustomerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CustomerPanelLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel3.add(CustomerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 244, 250, -1));

        LogoutPanel.setBackground(new java.awt.Color(99, 110, 114));
        LogoutPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LogoutPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LogoutPanelMouseExited(evt);
            }
        });
        LogoutPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("LOGOUT");
        LogoutPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/img/icons8_logout_rounded_left_26px.png"))); // NOI18N
        LogoutPanel.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, 30));

        jPanel3.add(LogoutPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 590, 170, 70));

        HoldOrderPanel.setBackground(new java.awt.Color(99, 110, 114));
        HoldOrderPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HoldOrderPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HoldOrderPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HoldOrderPanelMouseExited(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/BillingIMGs/icons8_anchor_64px.png"))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Hold Order");

        javax.swing.GroupLayout HoldOrderPanelLayout = new javax.swing.GroupLayout(HoldOrderPanel);
        HoldOrderPanel.setLayout(HoldOrderPanelLayout);
        HoldOrderPanelLayout.setHorizontalGroup(
            HoldOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HoldOrderPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))
        );
        HoldOrderPanelLayout.setVerticalGroup(
            HoldOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HoldOrderPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(HoldOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(HoldOrderPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 336, 250, 80));

        jPanel5.setBackground(new java.awt.Color(99, 110, 114));
        jPanel5.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Super");

        geelsSuperLabel.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        geelsSuperLabel.setForeground(new java.awt.Color(255, 255, 255));
        geelsSuperLabel.setText("Geels ");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(geelsSuperLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(geelsSuperLabel)
                    .addComponent(jLabel6))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 250, -1));

        LoadOrderPanel1.setBackground(new java.awt.Color(99, 110, 114));
        LoadOrderPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoadOrderPanel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LoadOrderPanel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LoadOrderPanel1MouseExited(evt);
            }
        });

        LoadOrderLable.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        LoadOrderLable.setForeground(new java.awt.Color(255, 255, 255));
        LoadOrderLable.setText("Load Order");

        LoadOrderIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/BillingIMGs/LoadOrder.png"))); // NOI18N

        javax.swing.GroupLayout LoadOrderPanel1Layout = new javax.swing.GroupLayout(LoadOrderPanel1);
        LoadOrderPanel1.setLayout(LoadOrderPanel1Layout);
        LoadOrderPanel1Layout.setHorizontalGroup(
            LoadOrderPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoadOrderPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LoadOrderIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LoadOrderLable, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))
        );
        LoadOrderPanel1Layout.setVerticalGroup(
            LoadOrderPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoadOrderPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LoadOrderPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LoadOrderLable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LoadOrderIcon))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(LoadOrderPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 250, -1));

        jLayeredPane1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 670));

        jPanel1.setBackground(new java.awt.Color(62, 74, 87));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(62, 74, 87));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        timeLabel.setForeground(new java.awt.Color(255, 255, 255));
        timeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        timeLabel.setText("02:03:55 PM");

        homeIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/BillingIMGs/icons8_home_page_32px_1.png"))); // NOI18N
        homeIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeIconMouseClicked(evt);
            }
        });

        printIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/BillingIMGs/icons8_print_32px.png"))); // NOI18N
        printIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                printIconMouseClicked(evt);
            }
        });

        userIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/BillingIMGs/icons8_male_user_32px.png"))); // NOI18N

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Lasith");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(283, 283, 283)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(userIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(homeIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(printIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(timeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(printIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(userIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(timeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                        .addComponent(jSeparator2)
                        .addComponent(jSeparator3)
                        .addComponent(jSeparator4))
                    .addComponent(homeIcon))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 600, -1));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 32, 613, 12));

        rslable.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        rslable.setForeground(new java.awt.Color(255, 255, 255));
        rslable.setText("RS:");
        jPanel1.add(rslable, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 597, 77, -1));

        TotalText.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        TotalText.setForeground(new java.awt.Color(255, 255, 255));
        TotalText.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        TotalText.setText("0.00");
        jPanel1.add(TotalText, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 597, 171, -1));

        totalLable.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        totalLable.setForeground(new java.awt.Color(255, 255, 255));
        totalLable.setText("Total");
        jPanel1.add(totalLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 597, 96, -1));

        billHeading.setBackground(new java.awt.Color(62, 74, 87));

        lableReciptNo.setForeground(new java.awt.Color(255, 255, 255));
        lableReciptNo.setText("Recipt NO:");

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Date:");

        reciptNoText.setForeground(new java.awt.Color(255, 255, 255));

        dateText.setForeground(new java.awt.Color(255, 255, 255));
        dateText.setText("2020-12-15 ");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cashier:");

        cashierNameText.setForeground(new java.awt.Color(255, 255, 255));

        customerLabel.setForeground(new java.awt.Color(255, 255, 255));
        customerLabel.setText("Customer");

        timeText.setForeground(new java.awt.Color(255, 255, 255));
        timeText.setText("02:13:50 ");

        customerTxt.setForeground(new java.awt.Color(255, 255, 255));
        customerTxt.setText("Guest");

        javax.swing.GroupLayout billHeadingLayout = new javax.swing.GroupLayout(billHeading);
        billHeading.setLayout(billHeadingLayout);
        billHeadingLayout.setHorizontalGroup(
            billHeadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(billHeadingLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(billHeadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(billHeadingLayout.createSequentialGroup()
                        .addComponent(lableReciptNo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(reciptNoText, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(billHeadingLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cashierNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 156, Short.MAX_VALUE)
                .addGroup(billHeadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(billHeadingLayout.createSequentialGroup()
                        .addComponent(customerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(customerTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(billHeadingLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dateText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(timeText)))
                .addGap(46, 46, 46))
        );
        billHeadingLayout.setVerticalGroup(
            billHeadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(billHeadingLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(billHeadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(timeText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(billHeadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lableReciptNo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(reciptNoText, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dateText, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(billHeadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(billHeadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cashierNameText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(customerLabel)
                        .addComponent(customerTxt))
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel1.add(billHeading, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 55, -1, -1));

        BillPanel.setBackground(new java.awt.Color(62, 74, 87));
        BillPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        scanLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        scanLabel.setForeground(new java.awt.Color(255, 255, 255));
        scanLabel.setText("Scan Or Enter the Code");

        codeInput.setBackground(new java.awt.Color(204, 204, 204));
        codeInput.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        codeInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                codeInputKeyPressed(evt);
            }
        });

        qtyLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        qtyLabel.setForeground(new java.awt.Color(255, 255, 255));
        qtyLabel.setText("Quantity");

        qtyInputLabel.setBackground(new java.awt.Color(204, 204, 204));
        qtyInputLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        qtyInputLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                qtyInputLabelMousePressed(evt);
            }
        });
        qtyInputLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtyInputLabelActionPerformed(evt);
            }
        });
        qtyInputLabel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                qtyInputLabelKeyPressed(evt);
            }
        });

        insertPanel.setBackground(new java.awt.Color(153, 153, 153));
        insertPanel.setForeground(new java.awt.Color(204, 204, 204));
        insertPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                insertPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                insertPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                insertPanelMouseExited(evt);
            }
        });
        insertPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("INSERT");
        insertPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, 20));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/BillingIMGs/icons8_more_details_32px.png"))); // NOI18N
        insertPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 42));

        AddCusPanel.setBackground(new java.awt.Color(0, 51, 204));
        AddCusPanel.setForeground(new java.awt.Color(204, 204, 204));
        AddCusPanel.setPreferredSize(new java.awt.Dimension(107, 42));
        AddCusPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddCusPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AddCusPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AddCusPanelMouseExited(evt);
            }
        });
        AddCusPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AddCusLabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        AddCusLabel.setForeground(new java.awt.Color(255, 255, 255));
        AddCusLabel.setText("Customer");
        AddCusPanel.add(AddCusLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, 40));

        AddCusIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/BillingIMGs/icons8_add_user_male_32px.png"))); // NOI18N
        AddCusPanel.add(AddCusIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 40));

        javax.swing.GroupLayout BillPanelLayout = new javax.swing.GroupLayout(BillPanel);
        BillPanel.setLayout(BillPanelLayout);
        BillPanelLayout.setHorizontalGroup(
            BillPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BillPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BillPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(qtyLabel)
                    .addComponent(scanLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(BillPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(qtyInputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codeInput, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addGroup(BillPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(insertPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AddCusPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        BillPanelLayout.setVerticalGroup(
            BillPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BillPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BillPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BillPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(BillPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AddCusPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(scanLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(codeInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(BillPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BillPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(qtyInputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(qtyLabel))
                    .addComponent(insertPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(BillPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 444, -1, 112));

        DisplayItems.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Name", "ProCode", "QTY", "Unit Price", "Total"
            }
        ));
        DisplayItems.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DisplayItemsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(DisplayItems);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 118, 595, 152));

        ItemDetailsAreaPanel.setBackground(new java.awt.Color(62, 74, 87));
        ItemDetailsAreaPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        ItemDetailsAreaPanel.setForeground(new java.awt.Color(255, 255, 255));

        ItemIDText.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ItemIDText.setForeground(new java.awt.Color(255, 255, 255));
        ItemIDText.setText("ITEM ID:");

        ItemNameLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ItemNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        ItemNameLabel.setText("ITEM NAME:");

        ItemTypeLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ItemTypeLabel.setForeground(new java.awt.Color(255, 255, 255));
        ItemTypeLabel.setText("ITEM TYPE:");

        ItemNameDisplay.setBackground(new java.awt.Color(62, 74, 87));
        ItemNameDisplay.setColumns(5);
        ItemNameDisplay.setForeground(new java.awt.Color(255, 255, 255));
        ItemNameDisplay.setLineWrap(true);
        ItemNameDisplay.setRows(2);
        ItemNameDisplay.setWrapStyleWord(true);
        jScrollPane2.setViewportView(ItemNameDisplay);

        ItemTypeDisplay.setBackground(new java.awt.Color(62, 74, 87));
        ItemTypeDisplay.setForeground(new java.awt.Color(255, 255, 255));
        ItemTypeDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemTypeDisplayActionPerformed(evt);
            }
        });

        ItemIDDisplay1.setBackground(new java.awt.Color(62, 74, 87));
        ItemIDDisplay1.setForeground(new java.awt.Color(255, 255, 255));
        ItemIDDisplay1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemIDDisplay1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ItemDetailsAreaPanelLayout = new javax.swing.GroupLayout(ItemDetailsAreaPanel);
        ItemDetailsAreaPanel.setLayout(ItemDetailsAreaPanelLayout);
        ItemDetailsAreaPanelLayout.setHorizontalGroup(
            ItemDetailsAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ItemDetailsAreaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ItemDetailsAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ItemNameLabel)
                    .addComponent(ItemIDText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ItemDetailsAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ItemIDDisplay1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ItemTypeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ItemTypeDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );
        ItemDetailsAreaPanelLayout.setVerticalGroup(
            ItemDetailsAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ItemDetailsAreaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ItemDetailsAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ItemIDDisplay1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(ItemDetailsAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ItemIDText)
                        .addComponent(ItemTypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ItemTypeDisplay))
                .addGap(30, 30, 30)
                .addGroup(ItemDetailsAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ItemDetailsAreaPanelLayout.createSequentialGroup()
                        .addComponent(ItemNameLabel)
                        .addGap(0, 31, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );

        jPanel1.add(ItemDetailsAreaPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 281, -1, 145));

        printPanel.setBackground(new java.awt.Color(102, 102, 102));
        printPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                printPanelMouseClicked(evt);
            }
        });

        PrintBill.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/BillingIMGs/icons8_print_32px.png"))); // NOI18N

        jLabel12.setFont(new java.awt.Font("Arial", 0, 23)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("PRINT");

        javax.swing.GroupLayout printPanelLayout = new javax.swing.GroupLayout(printPanel);
        printPanel.setLayout(printPanelLayout);
        printPanelLayout.setHorizontalGroup(
            printPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(printPanelLayout.createSequentialGroup()
                .addComponent(PrintBill)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        printPanelLayout.setVerticalGroup(
            printPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(printPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(PrintBill, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, printPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addContainerGap())
        );

        jPanel1.add(printPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 590, 120, 59));

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator6.setAlignmentX(1.0F);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private String[][] hold;
    private String HoldCusName;
    private boolean state = false;
    private void saveData(){
       DefaultTableModel tb = (DefaultTableModel)DisplayItems.getModel();
       hold = new String[tb.getRowCount()][5];
       HoldCusName = customerTxt.getText();
        for (int i=0; i<tb.getRowCount(); i++){
            for (int k=0; k<5; k++){
                hold[i][k] = tb.getValueAt(i, k).toString();
            } 
        }
        state = true;
    }
    private void loadData(){
        DefaultTableModel tb = (DefaultTableModel)DisplayItems.getModel();
        customerTxt.setText(HoldCusName);
           for (String[] hold1 : hold) {
               tb.addRow(hold1);
           }
        state = false;
    }
    private  void clear(){
        ((DefaultTableModel)DisplayItems.getModel()).setRowCount(0);
        customerTxt.setText(" ");
        ItemIDDisplay1.setText("");
        ItemNameDisplay.setText("");
        ItemTypeDisplay.setText("");
        codeInput.setText("");
        TotalText.setText("0.00");
    }
    private String calTotal(){
        double total=0;
        DefaultTableModel tb = (DefaultTableModel)DisplayItems.getModel();
        for (int i=0; i<tb.getRowCount(); i++){
            total+=Double.valueOf(tb.getValueAt(i, 4).toString());
        }
        return Double.toString(total);
    }
    private void setDate(){
        Date today = new Date();
        SimpleDateFormat date = new SimpleDateFormat("yyyy-MM-dd");  
        dateText.setText(date.format(today));
    }
    

    private void insertPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_insertPanelMouseClicked
        //TAKE THE CODE
        //TAKE THE QUANTITY
        //log details in the table
        //SET FOCUS TO CODE AGAIN
        String code= codeInput.getText();
        try {
            int quantity = Integer.valueOf(qtyInputLabel.getText());
            Product.setProductDetails(code,DisplayItems,quantity,ItemTypeDisplay,ItemNameDisplay);
            TotalText.setText(calTotal());
            ItemIDDisplay1.setText(code);
            codeInput.setText("");
            qtyInputLabel.setText("1");

        }catch(NumberFormatException e){
            new InputError("Quantity Field","Please insert valid quantity to proceed").setVisible(true);
        }
        
        //calculating the total

    }//GEN-LAST:event_insertPanelMouseClicked

    private void qtyInputLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtyInputLabelActionPerformed

    }//GEN-LAST:event_qtyInputLabelActionPerformed

    private void ItemTypeDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemTypeDisplayActionPerformed

    }//GEN-LAST:event_ItemTypeDisplayActionPerformed

    private void ItemIDDisplay1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemIDDisplay1ActionPerformed

    }//GEN-LAST:event_ItemIDDisplay1ActionPerformed

    private void qtyInputLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_qtyInputLabelMousePressed
        qtyInputLabel.setText("");
    }//GEN-LAST:event_qtyInputLabelMousePressed

    private void AddCusPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddCusPanelMouseClicked
        //allows to select a customer
        selectCustomer newCus = new selectCustomer();
        newCus.setVisible(true);
        customerTxt.setText(newCus.getCusName());
        CusID = newCus.getCusID();
    }//GEN-LAST:event_AddCusPanelMouseClicked

    private void NewOrderMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewOrderMouseEntered
        NewOrder.setBackground(new Color(62,74,87));
    }//GEN-LAST:event_NewOrderMouseEntered

    private void NewOrderMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewOrderMouseExited
        NewOrder.setBackground(new Color(99,110,114));
    }//GEN-LAST:event_NewOrderMouseExited

    private void CustomerPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CustomerPanelMouseEntered
        CustomerPanel.setBackground(new Color(62,74,87));
    }//GEN-LAST:event_CustomerPanelMouseEntered

    private void CustomerPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CustomerPanelMouseExited
        CustomerPanel.setBackground(new Color(99,110,114));
    }//GEN-LAST:event_CustomerPanelMouseExited

    private void HoldOrderPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HoldOrderPanelMouseEntered
        HoldOrderPanel.setBackground(new Color(62,74,87));
    }//GEN-LAST:event_HoldOrderPanelMouseEntered

    private void HoldOrderPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HoldOrderPanelMouseExited
        if(state){
            HoldOrderPanel.setBackground(new Color(62,74,87));
        }
        else{
            HoldOrderPanel.setBackground(new Color(99,110,114));
        }
    }//GEN-LAST:event_HoldOrderPanelMouseExited

    private void LogoutPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutPanelMouseEntered
        LogoutPanel.setBackground(new Color(62,74,87));
    }//GEN-LAST:event_LogoutPanelMouseEntered

    private void LogoutPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutPanelMouseClicked
        // TODO add your handling code here:
        this.remove(jPanel1);
        new logoutAlert(this,jPanel1).setVisible(true);
    }//GEN-LAST:event_LogoutPanelMouseClicked

    private void LogoutPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutPanelMouseExited
        // TODO add your handling code here:
        LogoutPanel.setBackground(new Color(99,110,114));
    }//GEN-LAST:event_LogoutPanelMouseExited

    private void AddCusPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddCusPanelMouseEntered
        // TODO add your handling code here:
        AddCusPanel.setBackground(new Color(0,153,204));
    }//GEN-LAST:event_AddCusPanelMouseEntered

    private void AddCusPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddCusPanelMouseExited
        // TODO add your handling code here:
        AddCusPanel.setBackground(new Color(0,51,204));
    }//GEN-LAST:event_AddCusPanelMouseExited

    private void insertPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_insertPanelMouseEntered
        // TODO add your handling code here:
        insertPanel.setBackground(new Color(120,120,120));
    }//GEN-LAST:event_insertPanelMouseEntered

    private void insertPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_insertPanelMouseExited
        // TODO add your handling code here:
        insertPanel.setBackground(new Color(153,153,153));
    }//GEN-LAST:event_insertPanelMouseExited

    private void printPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printPanelMouseClicked
        // TODO add your handling code here:
        DefaultTableModel saveOrder = (DefaultTableModel) DisplayItems.getModel();
        //reduce quantites from the product table to maintain the inventory
        try{
            Payment.DeductItems(saveOrder);
            int ID = Payment.getID();
            //allows to create an auto increment value.
            //the same id is used to save details in the payment details table.
            //filling the payment details table 
            Payment.UpdatePayment(ID, CusID, dateText.getText(), timeText.getText(), TotalText.getText(), UsrID);
            payment_details.Update_Payment_Details(saveOrder, ID);
            //print bill
            PrintBill bill = new PrintBill(reciptNoText.getText(), dateText.getText()+" "+timeText.getText(), cashierNameText.getText(), customerTxt.getText(),TotalText.getText(),DisplayItems);
            bill.setVisible(true);
            if (bill.getCompleted()){
                clear();
                reciptNoText.setText(Integer.toString(ID));
            }
        }catch(SQLException e){
            //e.printStackTrace();
           new dbErrorNonExitOnClose().setVisible(true);
        }
        
    }//GEN-LAST:event_printPanelMouseClicked

    private void NewOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewOrderMouseClicked
        // TODO add your handling code here:
        OnCloseAlert alt = new OnCloseAlert();
        alt.setVisible(true);
        if(alt.getAction()){
            //clearing table and updating the date time
            clear();
            setDate();
            
        }
        //Update date and time.
        
        
    }//GEN-LAST:event_NewOrderMouseClicked

    private void DisplayItemsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DisplayItemsMouseClicked
        // TODO add your handling code here:

        ItemDetailsPopUp details = new ItemDetailsPopUp(DisplayItems.getValueAt(DisplayItems.getSelectedRow(), 0).toString(),DisplayItems.getValueAt(DisplayItems.getSelectedRow(), 2).toString());
        details.setVisible(true);
        
        switch(details.getAction()){
        
            case 1:
                DisplayItems.clearSelection();
                break;
            case 2:
                ((DefaultTableModel)DisplayItems.getModel()).removeRow(DisplayItems.getSelectedRow());
                break;
            case 3:
                DisplayItems.setValueAt(details.getQuantity(), DisplayItems.getSelectedRow(), 2);
                DisplayItems.setValueAt(Integer.valueOf(details.getQuantity())*Double.valueOf(DisplayItems.getValueAt(DisplayItems.getSelectedRow(), 3).toString()), DisplayItems.getSelectedRow(), 4);
                double total=0;
                for (int i=0; i<DisplayItems.getRowCount(); i++){
                    total+=Double.valueOf(DisplayItems.getValueAt(i, 4).toString());
                }
                TotalText.setText(Double.toString(total));
                break;
        
        }
        
    }//GEN-LAST:event_DisplayItemsMouseClicked

    private void HoldOrderPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HoldOrderPanelMouseClicked
        // TODO add your handling code here:
        if(!state){
            HoldOrderPanel.setBackground(new Color(62,74,87));
            saveData();
            clear();
            setDate();
            
        }
        
    }//GEN-LAST:event_HoldOrderPanelMouseClicked

    private void LoadOrderPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoadOrderPanel1MouseClicked
        // TODO add your handling code here
        if(state){
            HoldOrderPanel.setBackground(new Color(99,110,114));
            clear();
            loadData();
            setDate();
            TotalText.setText(calTotal());
        }
    }//GEN-LAST:event_LoadOrderPanel1MouseClicked

    private void LoadOrderPanel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoadOrderPanel1MouseEntered
        // TODO add your handling code here:
        LoadOrderPanel1.setBackground(new Color(62,74,87));
    }//GEN-LAST:event_LoadOrderPanel1MouseEntered

    private void LoadOrderPanel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoadOrderPanel1MouseExited
        // TODO add your handling code here:
        LoadOrderPanel1.setBackground(new Color(99,110,114));
    }//GEN-LAST:event_LoadOrderPanel1MouseExited

    private void codeInputKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codeInputKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER){
            String code= codeInput.getText();
        try {
            int quantity = Integer.valueOf(qtyInputLabel.getText());
            Product.setProductDetails(code,DisplayItems,quantity,ItemTypeDisplay,ItemNameDisplay);
            TotalText.setText(calTotal());
            ItemIDDisplay1.setText(code);
            codeInput.setText("");
            qtyInputLabel.setText("1");

        }catch(NumberFormatException e){
            new InputError("Quantity Field","Please insert valid quantity to proceed").setVisible(true);
        }
        }
    }//GEN-LAST:event_codeInputKeyPressed

    private void qtyInputLabelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qtyInputLabelKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER){
            String code= codeInput.getText();
        try {
            int quantity = Integer.valueOf(qtyInputLabel.getText());
            Product.setProductDetails(code,DisplayItems,quantity,ItemTypeDisplay,ItemNameDisplay);
            TotalText.setText(calTotal());
            ItemIDDisplay1.setText(code);
            codeInput.setText("");
            qtyInputLabel.setText("1");

        }catch(NumberFormatException e){
            new InputError("Quantity Field","Please insert valid quantity to proceed").setVisible(true);
        }
        }
    }//GEN-LAST:event_qtyInputLabelKeyPressed

    private void CustomerPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CustomerPanelMouseClicked
        // TODO add your handling code here:
        new ShowCustomers().setVisible(true);
    }//GEN-LAST:event_CustomerPanelMouseClicked

    private void printIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printIconMouseClicked
        // TODO add your handling code here:
        // TODO add your handling code here:
        DefaultTableModel saveOrder = (DefaultTableModel) DisplayItems.getModel();
        //reduce quantites from the product table to maintain the inventory
        try{
            Payment.DeductItems(saveOrder);
            int ID = Payment.getID();
            //allows to create an auto increment value.
            //the same id is used to save details in the payment details table.
            //filling the payment details table 
            Payment.UpdatePayment(ID, CusID, dateText.getText(), timeText.getText(), TotalText.getText(), UsrID);
            payment_details.Update_Payment_Details(saveOrder, ID);
            //print bill
            PrintBill bill = new PrintBill(reciptNoText.getText(), dateText.getText()+" "+timeText.getText(), cashierNameText.getText(), customerTxt.getText(),TotalText.getText(),DisplayItems);
            bill.setVisible(true);
            if (bill.getCompleted()){
                clear();
                reciptNoText.setText(Integer.toString(ID));
            }
        }catch(SQLException e){
            //e.printStackTrace();
           new dbErrorNonExitOnClose().setVisible(true);
        }
    }//GEN-LAST:event_printIconMouseClicked

    private void homeIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeIconMouseClicked
        // TODO add your handling code here:
        this.remove(jPanel1);
        new logoutAlert(this,jPanel1).setVisible(true);
    }//GEN-LAST:event_homeIconMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BillingInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BillingInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BillingInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BillingInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BillingInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddCusIcon;
    private javax.swing.JLabel AddCusLabel;
    private javax.swing.JPanel AddCusPanel;
    private javax.swing.JPanel BillPanel;
    private javax.swing.JPanel CustomerPanel;
    private javax.swing.JTable DisplayItems;
    private javax.swing.JPanel HoldOrderPanel;
    private javax.swing.JPanel ItemDetailsAreaPanel;
    private javax.swing.JTextField ItemIDDisplay1;
    private javax.swing.JLabel ItemIDText;
    private javax.swing.JTextArea ItemNameDisplay;
    private javax.swing.JLabel ItemNameLabel;
    private javax.swing.JTextField ItemTypeDisplay;
    private javax.swing.JLabel ItemTypeLabel;
    private javax.swing.JLabel LoadOrderIcon;
    private javax.swing.JLabel LoadOrderLable;
    private javax.swing.JPanel LoadOrderPanel1;
    private javax.swing.JPanel LogoutPanel;
    private javax.swing.JPanel NewOrder;
    private javax.swing.JLabel PrintBill;
    private javax.swing.JLabel TotalText;
    private javax.swing.JPanel billHeading;
    private javax.swing.JLabel cashierNameText;
    private javax.swing.JTextField codeInput;
    private javax.swing.JLabel customerLabel;
    private javax.swing.JLabel customerTxt;
    private javax.swing.JLabel dateText;
    private javax.swing.JLabel geelsSuperLabel;
    private javax.swing.JLabel homeIcon;
    private javax.swing.JPanel insertPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel lableReciptNo;
    private javax.swing.JLabel logout;
    private javax.swing.JLabel newOrderIcon;
    private javax.swing.JLabel newOrderText;
    private javax.swing.JLabel printIcon;
    private javax.swing.JPanel printPanel;
    private javax.swing.JTextField qtyInputLabel;
    private javax.swing.JLabel qtyLabel;
    private javax.swing.JLabel reciptNoText;
    private javax.swing.JLabel rslable;
    private javax.swing.JLabel scanLabel;
    private javax.swing.JLabel timeLabel;
    private javax.swing.JLabel timeText;
    private javax.swing.JLabel totalLable;
    private javax.swing.JLabel userIcon;
    // End of variables declaration//GEN-END:variables
}
