/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

/**
 *
 * @author Lasith
 */
public class BillingInterface extends javax.swing.JFrame {

    /**
     * Creates new form Billing
     */
    public BillingInterface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel1 = new javax.swing.JPanel();
        cusOrderPanel = new javax.swing.JPanel();
        cusOrderLable = new javax.swing.JLabel();
        cusOrderEditPanle = new javax.swing.JPanel();
        editCusOrder = new javax.swing.JLabel();
        cusSearcPanel = new javax.swing.JPanel();
        cusSearchLable = new javax.swing.JLabel();
        searchCusOrderPanel = new javax.swing.JPanel();
        searchCusOrderLable = new javax.swing.JLabel();
        searchCusOrderPanel1 = new javax.swing.JPanel();
        searchCusOrderLable1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        geelsSuperLabel = new javax.swing.JLabel();
        lableReciptNo = new javax.swing.JLabel();
        reciptNoText = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        dateText = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cashierNameText = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        totalLable = new javax.swing.JLabel();
        TotalText = new javax.swing.JLabel();
        rslable = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(62, 74, 87));

        cusOrderPanel.setBackground(new java.awt.Color(51, 204, 0));

        cusOrderLable.setBackground(new java.awt.Color(255, 255, 255));
        cusOrderLable.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        cusOrderLable.setForeground(new java.awt.Color(255, 255, 255));
        cusOrderLable.setText("Create Customer Order");

        javax.swing.GroupLayout cusOrderPanelLayout = new javax.swing.GroupLayout(cusOrderPanel);
        cusOrderPanel.setLayout(cusOrderPanelLayout);
        cusOrderPanelLayout.setHorizontalGroup(
            cusOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cusOrderPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cusOrderLable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        cusOrderPanelLayout.setVerticalGroup(
            cusOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cusOrderLable, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
        );

        cusOrderEditPanle.setBackground(new java.awt.Color(255, 102, 0));

        editCusOrder.setBackground(new java.awt.Color(255, 255, 255));
        editCusOrder.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        editCusOrder.setForeground(new java.awt.Color(255, 255, 255));
        editCusOrder.setText("Edit Customer Order");

        javax.swing.GroupLayout cusOrderEditPanleLayout = new javax.swing.GroupLayout(cusOrderEditPanle);
        cusOrderEditPanle.setLayout(cusOrderEditPanleLayout);
        cusOrderEditPanleLayout.setHorizontalGroup(
            cusOrderEditPanleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cusOrderEditPanleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(editCusOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        cusOrderEditPanleLayout.setVerticalGroup(
            cusOrderEditPanleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(editCusOrder, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
        );

        cusSearcPanel.setBackground(new java.awt.Color(255, 0, 51));

        cusSearchLable.setBackground(new java.awt.Color(255, 255, 255));
        cusSearchLable.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        cusSearchLable.setForeground(new java.awt.Color(255, 255, 255));
        cusSearchLable.setText("Customer Search");

        javax.swing.GroupLayout cusSearcPanelLayout = new javax.swing.GroupLayout(cusSearcPanel);
        cusSearcPanel.setLayout(cusSearcPanelLayout);
        cusSearcPanelLayout.setHorizontalGroup(
            cusSearcPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cusSearcPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cusSearchLable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        cusSearcPanelLayout.setVerticalGroup(
            cusSearcPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cusSearchLable, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
        );

        searchCusOrderPanel.setBackground(new java.awt.Color(255, 0, 255));

        searchCusOrderLable.setBackground(new java.awt.Color(255, 255, 255));
        searchCusOrderLable.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        searchCusOrderLable.setForeground(new java.awt.Color(255, 255, 255));
        searchCusOrderLable.setText("Search Customer Order");

        javax.swing.GroupLayout searchCusOrderPanelLayout = new javax.swing.GroupLayout(searchCusOrderPanel);
        searchCusOrderPanel.setLayout(searchCusOrderPanelLayout);
        searchCusOrderPanelLayout.setHorizontalGroup(
            searchCusOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchCusOrderPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchCusOrderLable, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                .addContainerGap())
        );
        searchCusOrderPanelLayout.setVerticalGroup(
            searchCusOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(searchCusOrderLable, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
        );

        searchCusOrderPanel1.setBackground(new java.awt.Color(15, 158, 15));

        searchCusOrderLable1.setBackground(new java.awt.Color(255, 255, 255));
        searchCusOrderLable1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        searchCusOrderLable1.setForeground(new java.awt.Color(255, 255, 255));
        searchCusOrderLable1.setText("Open Item");

        javax.swing.GroupLayout searchCusOrderPanel1Layout = new javax.swing.GroupLayout(searchCusOrderPanel1);
        searchCusOrderPanel1.setLayout(searchCusOrderPanel1Layout);
        searchCusOrderPanel1Layout.setHorizontalGroup(
            searchCusOrderPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchCusOrderPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(searchCusOrderLable1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        searchCusOrderPanel1Layout.setVerticalGroup(
            searchCusOrderPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(searchCusOrderLable1, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(searchCusOrderPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cusOrderPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cusOrderEditPanle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cusSearcPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(searchCusOrderPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(371, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(cusOrderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(cusOrderEditPanle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cusSearcPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(searchCusOrderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(searchCusOrderPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(199, Short.MAX_VALUE))
        );

        jLayeredPane1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, -1, -1));

        jPanel3.setBackground(new java.awt.Color(62, 74, 87));

        geelsSuperLabel.setFont(new java.awt.Font("Leelawadee", 1, 36)); // NOI18N
        geelsSuperLabel.setForeground(new java.awt.Color(255, 255, 255));
        geelsSuperLabel.setText("Geels Super");

        lableReciptNo.setForeground(new java.awt.Color(255, 255, 255));
        lableReciptNo.setText("Recipt NO:");

        reciptNoText.setForeground(new java.awt.Color(255, 255, 255));
        reciptNoText.setText("5645646");

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Date:");

        dateText.setForeground(new java.awt.Color(255, 255, 255));
        dateText.setText("Mar-15-2020  02:55:13 PM");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cashier:");

        cashierNameText.setForeground(new java.awt.Color(255, 255, 255));
        cashierNameText.setText("Lasith");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Product Name", "Unit Price", "QTY", "Total"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        totalLable.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        totalLable.setForeground(new java.awt.Color(255, 255, 255));
        totalLable.setText("Total");

        TotalText.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        TotalText.setForeground(new java.awt.Color(255, 255, 255));
        TotalText.setText("5456456");

        rslable.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        rslable.setForeground(new java.awt.Color(255, 255, 255));
        rslable.setText("RS:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(geelsSuperLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lableReciptNo, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cashierNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(reciptNoText, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateText, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(totalLable, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91)
                        .addComponent(rslable, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TotalText, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(geelsSuperLabel)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lableReciptNo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reciptNoText, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cashierNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateText, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 212, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalLable, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rslable, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TotalText, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        jLayeredPane1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1085, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 654, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BillingInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BillingInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BillingInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BillingInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BillingInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TotalText;
    private javax.swing.JLabel cashierNameText;
    private javax.swing.JPanel cusOrderEditPanle;
    private javax.swing.JLabel cusOrderLable;
    private javax.swing.JPanel cusOrderPanel;
    private javax.swing.JPanel cusSearcPanel;
    private javax.swing.JLabel cusSearchLable;
    private javax.swing.JLabel dateText;
    private javax.swing.JLabel editCusOrder;
    private javax.swing.JLabel geelsSuperLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lableReciptNo;
    private javax.swing.JLabel reciptNoText;
    private javax.swing.JLabel rslable;
    private javax.swing.JLabel searchCusOrderLable;
    private javax.swing.JLabel searchCusOrderLable1;
    private javax.swing.JPanel searchCusOrderPanel;
    private javax.swing.JPanel searchCusOrderPanel1;
    private javax.swing.JLabel totalLable;
    // End of variables declaration//GEN-END:variables
}
