/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;


import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Font;
import java.awt.Window;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
/**
 *
 * @author dinuka
 */

public class PrintBill extends javax.swing.JDialog {
    String receiptNo;
    String billtxt = "";
    private boolean completed;
    public PrintBill() {
        super((Window)null);
        setModal(true);
        initComponents();
    }

    public PrintBill(String receiptNumber,String date, String cashierName, String customerName,String total, JTable table) {
        super((Window)null);
        setModal(true);
        initComponents();
        receiptNo=receiptNumber;
        receiptNumber=" Receipt No: "+receiptNumber;
        date=" Date: "+date;
        cashierName=" Cashier: "+cashierName;
        customerName= " Customer: "+customerName;
        String totalBill=" -------------------------------------------\n Total:";
        totalBill+=format("Rs:"+total, 37);
        billtxt = (" -------------------------------------------\n"+format("Geels Super", 25)+"\n -------------------------------------------\n"+receiptNumber+"\n"+date+"\n"+cashierName+"\n"+customerName);
        
        DefaultTableModel model=(DefaultTableModel)table.getModel();
        int numberOfRaws= table.getRowCount();
        billtxt+="\n -------------------------------------------\n";
        for(int x=0;x<numberOfRaws;x++){
            billtxt+=" "+model.getValueAt(x, 0).toString()+"\n";
            billtxt+=format(model.getValueAt(x, 3).toString()+"*"+model.getValueAt(x, 2), 20)+" ";
            billtxt+=format(model.getValueAt(x, 4).toString(), 23)+"\n";
        }
        billtxt+=totalBill;
        billtxt+=("\n -------------------------------------------\n"+format("Thank You..!", 26));
        preview.setText(billtxt);
    }
    public boolean getCompleted(){
        return completed;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        preview = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setUndecorated(true);

        preview.setFont(new Font(Font.MONOSPACED, Font.PLAIN, 12));
        preview.setColumns(20);
        preview.setRows(5);
        jScrollPane1.setViewportView(preview);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Print Preview");

        jButton1.setText("Print");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private String format(String str, int width){
        
        String output="";
        for (int i=0; i<width-(str.length()); i++){
            output+=" ";
        }
        output+=str;
        return output;
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      
        String filename="bill"+receiptNo+".pdf";
        Document doc = new Document();
        try { 
           PdfWriter.getInstance(doc, new FileOutputStream(filename));
           doc.open();
           com.itextpdf.text.Font myStyle = new com.itextpdf.text.Font();
           myStyle.setStyle("NORMAL");
           myStyle.setFamily("TIMES_ROMAN");
           Paragraph paragraph= new Paragraph(billtxt,myStyle);
           doc.add(paragraph);
           doc.close();
           completed = true;
        } catch (DocumentException | FileNotFoundException e) {
            //printError
        }
        
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrintBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrintBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrintBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrintBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrintBill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea preview;
    // End of variables declaration//GEN-END:variables
}
